name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set VERSION environment variable
        run: |
          echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Build container image with Maven
        run: mvn -B spring-boot:build-image -Dmaven.test.skip=true

      - name: Publish container image to Docker Hub
        run: |
          docker tag bookstore:${{ env.VERSION }} ${{ secrets.DOCKER_USERNAME }}/bookstore:${{ env.VERSION }}
          docker push ${{ secrets.DOCKER_USERNAME }}/bookstore:${{ env.VERSION }}
                
          docker tag bookstore:${{ env.VERSION }} ${{ secrets.DOCKER_USERNAME }}/bookstore:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/bookstore:latest
